name: Comment on Issues

on:
  workflow_dispatch:

jobs:
  comment-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Get open issues and comment if needed
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentBody = 'I have read it, in progress...';

            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const issue of issues) {
              if (issue.pull_request) continue;

              const comments = await github.paginate(github.rest.issues.listComments, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number
              });

              const alreadyCommented = comments.some(comment => comment.body === commentBody);

              if (!alreadyCommented) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: commentBody
                });
              }
            }
